### ISSUE TITLE
Problem with getting authors

### ISSUE THREAD

**Issue by yegorrybchenko** [frisoft/ateam#29]
After running:
```bash
RUST_BACKTRACE=1 ateam pr --org... --blame --tests-regex ... --label ... --regex-not ... --exclude-label ...
```
Got this error:
```
thread '<unnamed>' panicked at 'Can't get the authors for PROJECT_FILE, src/client/blame.rs:26:27
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I get this error time to time for always different files.

I collected full backtrace but I think it can't help (RUST_BACKTRACE=full):
```
thread '<unnamed>' panicked at 'Can't get the authors for PROJECT_FILE', src/client/blame.rs:26:27
stack backtrace:
   0:        0x10307cc54 - __mh_execute_header
   1:        0x10309affe - __mh_execute_header
   2:        0x103076056 - __mh_execute_header
   3:        0x10307ecd9 - __mh_execute_header
   4:        0x10307e7c0 - __mh_execute_header
   5:        0x10307f345 - __mh_execute_header
   6:        0x10307ee85 - __mh_execute_header
   7:        0x10307d0b8 - __mh_execute_header
   8:        0x10307edea - __mh_execute_header
   9:        0x1030b1c8b - __mh_execute_header
  10:        0x102d8d6d6 - __mh_execute_header
  11:        0x102da8ac6 - __mh_execute_header
  12:        0x102d897df - __mh_execute_header
  13:        0x102da276c - __mh_execute_header
  14:        0x102da8bd0 - __mh_execute_header
  15:        0x102da2710 - __mh_execute_header
  16:        0x102da8bd0 - __mh_execute_header
  17:        0x102da94cf - __mh_execute_header
  18:        0x102db99ea - __mh_execute_header
  19:        0x102d928d3 - __mh_execute_header
  20:        0x102dd0ad4 - __mh_execute_header
  21:        0x102d9ab68 - __mh_execute_header
  22:        0x102dd317a - __mh_execute_header
  23:        0x102da8d64 - __mh_execute_header
  24:        0x102da1e68 - __mh_execute_header
  25:        0x102da90e9 - __mh_execute_header
  26:        0x102da1e68 - __mh_execute_header
  27:        0x102da90e9 - __mh_execute_header
  28:        0x102dbba7c - __mh_execute_header
  29:        0x102d92019 - __mh_execute_header
  30:        0x1030ad8cf - __mh_execute_header
  31:        0x103016081 - __mh_execute_header
  32:        0x1030188e3 - __mh_execute_header
  33:        0x103018fb9 - __mh_execute_header
  34:        0x1030855ed - __mh_execute_header
  35:     0x7fff204638fc - __pthread_start
```

**Comment by frisoft** [comment]
Sorry for my very late reply.
It seems a problem in the Github GraphQL API. Is it still happening?

**Comment by frisoft** [comment]
Closing this as I think new versions may have resolved the issue.
Happy to reopen it if this is not the case.
